version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./docker/postgres:/data/postgres
    env_file:
    - .env
    networks:
      postgres:
        ipv4_address: 172.20.0.5
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./docker/pgadmin:/root/.pgadmin
    env_file:
    - .env
    networks:
      postgres:
        ipv4_address: 172.20.0.6
 
networks:
  postgres:
    ipam:
      config:
        - subnet: 172.20.0.0/24